### ISSUE TITLE
Minor: First sidebar entry and heading consistencies between Astra and Astra automation docs.

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/astra#79]
Page: [Astra Documentation](https://docs.netapp.com/us-en/astra/index.html)

We arrive at this page by clicking an "Astra docs" link in the sidebar. The page that displays says "Astra Documentation."

In the Astra automation docs, the sidebar entry says "Astra automation doc,"and the associated page says "Astra automation documentation."

- Looks like we need to agree on the first-level standard in the sidebar - singular (doc) or plural (docs).
- Should the heading on the home page use sentence style capitalization or cap each word?

**Comment by netapp-bcammett** [comment]
Thanks, Adam. The architects team will discuss and then we'll update the docs as needed.

**Comment by netapp-bcammett** [comment]
@dmp-netapp To get the Astra docs and Astra automation docs in alignment, we need to make these changes:

- **astra repo**: Change the page heading to "Astra documentation"
- **astra-automation repo**: Change the first entry in the sidebar to "Astra automation docs"

I'll make the astra repo update. Can you please make the astra-automation repo update?

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Thank you, @dmp-netapp 

Both sites are in sync now.
