### ISSUE TITLE
Provide actual hyperlink to https://cloud.netapp.com/astra on Astra home page

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/astra#91]
Page: [Astra Control Service documentation](https://docs.netapp.com/us-en/astra/index.html)

Is there a reason we don't offer an actual link here?

>> Go to https://cloud.netapp.com/astra to learn more.

**Comment by netapp-bcammett** [comment]
The link was removed from the intro text on the index page, so this is no longer an issue on the Astra Control Service docs.

Longer term, I filed an issue with our tools team for an enhancement to support links from that portion of the page.
